// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLGcnZaNdhs1zoZBhGNfoaIThQaDHu8yQ',
    appId: '1:1064399863768:web:13d38373bf24500de83cad',
    messagingSenderId: '1064399863768',
    projectId: 'app-parkio',
    authDomain: 'app-parkio.firebaseapp.com',
    storageBucket: 'app-parkio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUOCjMXtq9Hy2VaOuF-WycpscrFogZ3d0',
    appId: '1:1064399863768:android:cddff412fad869bfe83cad',
    messagingSenderId: '1064399863768',
    projectId: 'app-parkio',
    storageBucket: 'app-parkio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMB_wkByFJhSBEmKloKLLQapXtg0Zy1xE',
    appId: '1:1064399863768:ios:abfd0b59f4b93ccbe83cad',
    messagingSenderId: '1064399863768',
    projectId: 'app-parkio',
    storageBucket: 'app-parkio.firebasestorage.app',
    iosBundleId: 'app.parkio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMB_wkByFJhSBEmKloKLLQapXtg0Zy1xE',
    appId: '1:1064399863768:ios:abfd0b59f4b93ccbe83cad',
    messagingSenderId: '1064399863768',
    projectId: 'app-parkio',
    storageBucket: 'app-parkio.firebasestorage.app',
    iosBundleId: 'app.parkio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLGcnZaNdhs1zoZBhGNfoaIThQaDHu8yQ',
    appId: '1:1064399863768:web:f2bfd944d3be88b3e83cad',
    messagingSenderId: '1064399863768',
    projectId: 'app-parkio',
    authDomain: 'app-parkio.firebaseapp.com',
    storageBucket: 'app-parkio.firebasestorage.app',
  );
}
